Don't log to output folder directly, copy log on completion

diff --git a/bwa.task.yaml b/bwa.task.yaml
--- a/bwa.task.yaml
+++ b/bwa.task.yaml
@@ -73,8 +73,8 @@ parameters:
     value: "10000000"
 
 agent_requirements:
-  cpu_cores: 8 #64
-  memory_gb: 30 # 128
+  cpu_cores: 32
+  memory_gb: 64
   # agent_profile: azure_extra_large
 
 steps:
@@ -181,9 +181,9 @@ steps:
 
         workdir="/scratch"
         mkdir -p "$output_folder" || { echo "Failed to create output directory"; exit 1; }
-        logfile="$output_folder"/${sample_name}_bwa_run.log
-        exec > >(tee -a "$logfile") 2>&1 || { echo "Failed to redirect stdout and stderr to $logfile"; exit 1; }
         cd "$workdir" || { echo "Failed to change to output directory"; exit 1; }
+        logfile=${sample_name}_bwa_run.log
+        exec > >(tee -a "$logfile") 2>&1 || { echo "Failed to redirect stdout and stderr to $logfile"; exit 1; }
 
         # Print info
         echo "*************************"
@@ -378,3 +378,5 @@ steps:
           cp -r "$local_metrics_dir"/* "$metrics_dir/" || { echo "Failed to copy metrics to cloud storage"; exit 1; }
           echo "Metrics copied to cloud storage"
         fi
+
+        cp -f ${sample_name}_bwa_run.log "$output_folder"/
diff --git a/dnascope.task.yaml b/dnascope.task.yaml
--- a/dnascope.task.yaml
+++ b/dnascope.task.yaml
@@ -129,9 +129,9 @@ steps:
         echo "Starting analysis for $sample_name..."
 
         mkdir -p "$output_folder" || { echo "Failed to create output directory"; exit 1; }
-        logfile="$output_folder"/${sample_name}_dnascope_run.log
-        exec > >(tee -a "$logfile") 2>&1 || { echo "Failed to redirect stdout and stderr to $logfile"; exit 1; }
         cd "$workdir" || { echo "Failed to change to output directory"; exit 1; }
+        logfile=${sample_name}_dnascope_run.log
+        exec > >(tee -a "$logfile") 2>&1 || { echo "Failed to redirect stdout and stderr to $logfile"; exit 1; }
 
         # Copy input files to workdir for better performance
         echo "Copying input files to workdir..."
@@ -186,3 +186,4 @@ steps:
         duration=$((SECONDS - start_time))
         file_size=$(stat -c%s "${output_folder}/${sample_name}_dnascope.$output_suffix")
         echo "${sample_name}_dnascope.$output_suffix ($file_size bytes) called in $duration seconds"
+        cp -f ${sample_name}_dnascope_run.log "$output_folder"/
