Add `# shell` where missing and update miscellaneous paths and defaults

diff --git a/vspgx.task.yaml b/vspgx.task.yaml
--- a/vspgx.task.yaml
+++ b/vspgx.task.yaml
@@ -22,7 +22,7 @@ parameters:
 
   - name: project_name
     label: Project Name
-    help: The name of the VarSeq project to create
+    help: The name of the VarSeq project to create. If left blank, the name of the input folder will be used.
     type: string
     optional: true
 
@@ -31,6 +31,7 @@ parameters:
     help: The template to use for the VarSeq project
     type: file
     supports_location_mode: 'read_only'
+    path: AppData/VarSeq/User Data/ProjectTemplates/
 
   - name: overwrite_project
     label: Overwrite Existing VarSeq Projects
@@ -45,7 +46,7 @@ steps:
     docker:
       image: ${VSPIPELINE_DOCKER_IMAGE}
     args:
-      - |-
+      - |- # shell
         set -eu pipefail
 
         # Set up environment variables from workspace defaults
@@ -67,7 +68,7 @@ steps:
           exit 1
         fi
 
-        # Create parent directory if it doesn't exist, and check for project directory
+        # Create project directory if it doesn't exist, and check for project directory
         mkdir -p ${project_directory}
         if [[ -d "${project_directory}/${project_name}" && "${overwrite_project}" == "false" ]]; then
           echo "Project directory already exists and overwrite is set to false"
@@ -82,14 +83,19 @@ steps:
         echo "Running VSPipeline and creating VarSeq project"
         echo "Output path: ${project_directory}/${project_name}"
 
-        cd ${base_path}
-        vcf_files=$(find . -name "*.vcf.gz" -type f | paste -sd ',' - | sed 's/\([^,]*\)/"\1"/g')
+        cd "${base_path}"
+        variant_files=$(find . -name "*.vcf.gz" -type f | paste -sd ',' - | sed 's/\([^,]*\)/\1/g')
+
+        if [[ -z "${variant_files}" ]]; then
+          echo "No VCF files found in the specified directory."
+          exit 1
+        fi
 
         # Write the VSPipeline commands to a file
-        cat <<EOF > create-project.vs-batch
+        cat <<EOF > "${project_directory}/${project_name}.vs-batch"
         get_version
         project_create "${project_directory}/${project_name}" "${project_template}" ${overwrite_project:+overwrite=true}
-        import files="${vcf_files}" append_files_with_same_samples=True sample_fields_catalog=SampleCatalog
+        import files="${variant_files}" append_files_with_same_samples=True sample_fields_catalog=SampleCatalog
         download_required_sources
         task_wait
         get_task_list
@@ -97,6 +103,6 @@ steps:
         project_close
         EOF
 
-        /opt/vspipeline/vspipeline -c batch file=create-project.vs-batch || { echo "VSPipeline failed"; exit 1; }
+        /opt/vspipeline/vspipeline -c batch file="${project_directory}/${project_name}.vs-batch" || { echo "VSPipeline failed"; exit 1; }
 
-        rm -rf create-project.vs-batch
+        rm -rf "${project_directory}/${project_name}.vs-batch"
