Added PGx workflow, bumped up default VSPipeline task stats

diff --git a/vspgx.task.yaml b/vspgx.task.yaml
--- a/vspgx.task.yaml
+++ b/vspgx.task.yaml
@@ -1,5 +1,5 @@
-name: VSPipeline Create Project
-description: Create a VarSeq project from a template and input files
+name: VSPGx Create Project and Report
+description: Create a VarSeq PGx project from a template and input files
 auto_generate_session_for_account: "{workspaceBot}"
 
 agent_requirements:
@@ -22,7 +22,7 @@ parameters:
 
   - name: project_name
     label: Project Name
-    help: The name of the VarSeq project to create. If left blank, the name of the input folder will be used.
+    help: The name of the VarSeq project to create
     type: string
     optional: true
 
@@ -31,7 +31,6 @@ parameters:
     help: The template to use for the VarSeq project
     type: file
     supports_location_mode: 'read_only'
-    path: /AppData/VarSeq/User Data/ProjectTemplates/
 
   - name: overwrite_project
     label: Overwrite Existing VarSeq Projects
@@ -46,7 +45,7 @@ steps:
     docker:
       image: ${VSPIPELINE_DOCKER_IMAGE}
     args:
-      - |- # shell
+      - |-
         set -eu pipefail
 
         # Set up environment variables from workspace defaults
@@ -83,25 +82,21 @@ steps:
         echo "Running VSPipeline and creating VarSeq project"
         echo "Output path: ${project_directory}/${project_name}"
 
-        cd "${base_path}"
-        vcf_files=$(find . -name "*.vcf.gz" -type f | paste -sd ',' - | sed 's/\([^,]*\)/\1/g')
+        cd ${base_path}
+        vcf_files=$(find . -name "*.vcf.gz" -type f | paste -sd ',' - | sed 's/\([^,]*\)/"\1"/g')
 
-        if [[ -z "${vcf_files}" ]]; then
-          echo "No VCF files found in the specified directory."
-          exit 1
-        fi
-        
         # Write the VSPipeline commands to a file
-        cat <<EOF > "${project_directory}/${project_name}.vs-batch"
+        cat <<EOF > create-project.vs-batch
         get_version
         project_create "${project_directory}/${project_name}" "${project_template}" ${overwrite_project:+overwrite=true}
         import files="${vcf_files}" append_files_with_same_samples=True sample_fields_catalog=SampleCatalog
         download_required_sources
         task_wait
         get_task_list
+        run_project_report "PGX_Report_Template" true true
         project_close
         EOF
 
-        /opt/vspipeline/vspipeline -c batch file="${project_directory}/${project_name}.vs-batch" || { echo "VSPipeline failed"; exit 1; }
+        /opt/vspipeline/vspipeline -c batch file=create-project.vs-batch || { echo "VSPipeline failed"; exit 1; }
 
-        rm -rf "${project_directory}/${project_name}.vs-batch"
+        rm -rf create-project.vs-batch
